#include<iostream>
using namespace std;
int main()
{
    int a,b;
    cout<<"enter a numb"<<endl;
    cin>>a;
    cout<<"enter a numb"<<endl;
    cin>>b;
    cout<<"sum="<<a+b<<endl;
    cout<<"Subtract="<<a-b<<endl;
    cout<<"multiply="<<a*b<<endl;
    cout<<"Division="<<a/b<<endl;
    cout<<"Module="<<a%b<<endl;
     cout<<"Divide="<<a/b<<endl;
    cout<<"Module="<<a%b<<endl;
    return 0;
    
}

